// Mocks generated by Mockito 5.4.4 from annotations
// in catbreeds/test/unit_test/src/presentation/pages/home/cubit/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:catbreeds/src/config/failure.dart' as _i5;
import 'package:catbreeds/src/domain/entities/breed.dart' as _i6;
import 'package:catbreeds/src/domain/usecases/get_cat_breeds_use_case.dart'
    as _i3;
import 'package:catbreeds/src/domain/usecases/search_breed_use_case.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCatBreedsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCatBreedsUseCase extends _i1.Mock
    implements _i3.GetCatBreedsUseCase {
  MockGetCatBreedsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Breed>>> call(_i2.Unit? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Breed>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Breed>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Breed>>>);
}

/// A class which mocks [SearchBreedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchBreedUseCase extends _i1.Mock
    implements _i7.SearchBreedUseCase {
  MockSearchBreedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Breed>>> call(String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Breed>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Breed>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Breed>>>);
}
